apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-letskube
  labels:
    app: letskube
spec:
  replicas: 3
  template:
    metadata:
      name: letskube
      labels:
        app: letskube
    spec:
      containers:
      - name: letskube
        image: letskube:local
        imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: letskube


---

apiVersion: v1
kind: Service
metadata:
  name: letskube-service
spec:
  selector:
    app: letskube
  ports:
    - port: 80
  type: NodePort
  
  